WebApplication3/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Logging;
using WebApplication3.Data;
using WebApplication3.Hubs;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class PostController : Controller
    {
        private ApplicationDbContext db;
        private readonly ILogger<PostController> _logger;
        UserManager<ApplicationUser> _userManager;
        IHubContext<NotificationHub> _hubContext;
        public PostController(ILogger<PostController> logger, ApplicationDbContext context, 
            UserManager<ApplicationUser> userManager, IHubContext<NotificationHub> hubContext)
        {
            _logger = logger;
            db = context;
            _userManager = userManager;
            _hubContext = hubContext;   
        }
        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return View(db.Categories.ToList());
        }

        [HttpPost]
        public IActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                post.Author = _userManager.GetUserName(this.User);
                
                post.PostedOn = DateTime.Now;
                db.Posts.Add(post);
                db.SaveChanges();                
            }
            
            return RedirectPermanent("~/Home/Index");
        }       
    }
}

WebApplication3/Controllers/PostManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WebApplication3.Data;
using WebApplication3.Models;
using WebApplication3.Repository;

namespace WebApplication3.Controllers
{
    public class PostManagerController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private ApplicationDbContext db;
        private UserManager<ApplicationUser> _userManager;
        private INotificationRepository _notificationRepository;
        public PostManagerController(ILogger<HomeController> logger, ApplicationDbContext context, 
                                     UserManager<ApplicationUser> userManager, INotificationRepository notificationRepository)
        {
            _logger = logger;
            db = context;
            _userManager = userManager;
            _notificationRepository = notificationRepository;
        }
        public IActionResult Index()
        {
            var postCategoryVm = new CommentViewModel
            {
                Posts = db.Posts.ToList(),                
                Comments = db.Comments.ToList()
            };
            return View(postCategoryVm);
        }

        public IActionResult Details(int id, int postId)
        {
            var postCommentVm = new CommentViewModel
            {
                Post = db.Posts.Find(postId),
                //PostComment = new Comment {PostId = id}
                Comments = db.Comments.Where(c => c.PostId == postId).ToList()
            };

            return View(postCommentVm);
        }

        [HttpPost]
        public IActionResult Apply(int id)
        {
            if (ModelState.IsValid)
            {
                var post = db.Posts.Find(id);
                post.Posted = true;
                _logger.LogInformation(Request.Host.ToString());

                //var url = .ActionLink("Link", "Index", "Home");
                var url = "<a href='"
                    + Request.Scheme + "://"
                    + Request.Host 
                    + Request.PathBase
                    + @Url.RouteUrl(new { controller = "Home", action = "Details", id = id })
                    + $"'>{post.Title}</a>";
                string text = $"New article in category {db.Categories.Find(post.CategoryId).Title} has been already posted: {url}";
                _notificationRepository.Create(text, url);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            if (ModelState.IsValid)
            {
                db.Posts.Remove(db.Posts.Find(id));
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult ApplyComment(int id, int postId)
        {            
            if (ModelState.IsValid)
            {
                db.Comments.Find(id).CommentPosted = true;
                db.SaveChanges();
            }
            //return RedirectPermanent($"~/PostManager/Details/{postId}");
            return RedirectToAction("ManageComments", new { postIdManage = postId });
        }

        [HttpPost]
        public IActionResult RemoveComment(int id, int postId)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Remove(db.Comments.Find(id));
                db.SaveChanges();
            }
            return RedirectToAction("ManageComments", new { postIdManage = postId });
        }

        public PartialViewResult ManageComments(int postIdManage)
        {
            //var comments = db.Comments.Where(c => c.PostId == postIdManage).ToList();
            var postCommentVm = new CommentViewModel
            {
                Post = db.Posts.Find(postIdManage),
                //PostComment = new Comment {PostId = id}
                Comments = db.Comments.ToList()
            };
            return PartialView(postCommentVm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            await _userManager.DeleteAsync(_userManager.FindByIdAsync(id).Result);
            
            return RedirectToAction("ManageUsers");
        }


        public PartialViewResult ManageUsers()
        {
            return PartialView();
        }
    }
}

WebApplication3/Views/Shared/PostLastPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@model WebApplication3.Models.Post
<div class="wrapper">
    <p>
        @if (UserManager.FindByNameAsync(Model.Author).Result.ProfilePicture != null)
        {
            <img style="width:40px; height:40px; object-fit:cover; border-radius:30px" src="data:image/*;base64,@(Convert.ToBase64String(UserManager.FindByNameAsync(Model.Author).Result.ProfilePicture))">
        }
    </p>
    <p>@Model.Author</p>
    <p>@Model.PostedOn.ToString("dd MMM yyyy")</p>
    <h4>
        <a asp-controller="Home" asp-action="Details" asp-route-id="@Model.Id">
            @Model.Title
        </a>
    </h4>
    <textarea asp-for="ShortDescription" class="form-control" rows="3" readonly>
    <p>@Model.ShortDescription</p>
    </textarea>
    <hr />
</div>    

WebApplication3/Views/Shared/PostPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@model WebApplication3.Models.Post

<div class="page-wrapper">
    <div class="left-panel-wrapper">
        <div class="left-panel">
            <p>
                @if (UserManager.FindByNameAsync(Model.Author).Result.ProfilePicture != null)
                {
                    <img style="width:40px; height:40px; object-fit:cover; border-radius:30px" src="data:image/*;base64,@(Convert.ToBase64String(UserManager.FindByNameAsync(Model.Author).Result.ProfilePicture))">
                }
            </p>
            <p>@Model.Author</p>
            <p>@Model.PostedOn.ToString("dd MMM yyyy")</p>
        </div>
        <hr />
    </div>
    <div class="content-wrapper">
        <div class="content">                 
                <div class="input-group">
                    <h4>
                        <a asp-controller="Home" asp-action="Details" asp-route-id="@Model.Id">
                            @Model.Title
                        </a>
                    </h4>
                    <div method="post" asp-action="Delete" asp-controller="Home" asp-route-id="@Model.Id" asp-route-author="@Model.Author">
                        @if (UserManager.GetUserAsync(User).Result != null)
                        {
                            @if (UserManager.GetUserAsync(User).Result.UserName == Model.Author)
                            {
                                <span class="input-group-btn">
                                    <button class="btn btn-info">x</button>
                                </span>
                            }
                            
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <span class="input-group-btn">
                                <button class="btn btn-info">x</button>
                            </span>
                        }
                    </div>
                </div>
           
            <textarea asp-for="ShortDescription" class="form-control" rows="3" readonly>
            <p>@Model.ShortDescription</p>
            </textarea>
        </div>
    </div>
</div>

WebApplication3/Views/Shared/_CommentPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@model Comment
@{
    var mid = "myModal" + Model.CommentId;
    var tm = "#myModal" + Model.CommentId;
}


<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <b>@Model.CommentAuthor</b>
            <p><textarea class="form-control" readonly style="width: 450px">@Model.CContent</textarea></p>
            <p>@Model.PostedOn.ConvertTime(Context)</p>
            <p>
                <form method="post" asp-action="Like" asp-controller="Home" asp-route-CommentId="@Model.CommentId" asp-route-postId="@Model.PostId"
                      data-ajax="true" data-ajax-mode="replace" data-ajax-update="#comments" enctype="multipart/form-data">
                    @*<button class="btn btn-info">Like @Model.LikesCount</button>*@
                    <div class='like'>
                        @Model.LikesCount
                        <button class='like-toggle basic2'>♥</button>
                    </div>
                </form>
            </p>
            <hr />
        </div>
        <div class="col col-1">
            @if ((User.IsInRole("Admin") || User.IsInRole("Moderator")) && Model.CommentPosted == true)
            {
            <form method="post" asp-action="DeleteComment" asp-controller="Home" asp-route-id="@Model.CommentId" asp-route-postId="@Model.PostId"
                  data-ajax="true" data-ajax-mode="replace" data-ajax-update="#comments" enctype="multipart/form-data">
                <button class="close" data-toggle="modal" data-target="@tm" aria-hidden="true">&times;</button>

            </form>
            }
            @if (UserManager.GetUserAsync(User).Result != null && UserManager.GetUserAsync(User).Result.UserName == Model.CommentAuthor && !User.IsInRole("Admin") && !User.IsInRole("Moderator"))
            {
            <button class="close" data-toggle="modal" data-target="@tm" aria-hidden="true">&times;</button>
            <form method="post" asp-action="DeleteCommentUser" asp-controller="Home" asp-route-id="@Model.CommentId" asp-route-postId="@Model.PostId">
                <div class="modal fade" id="@mid" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="myModalLabel">Delete Confirmation</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            </div>
                            <div class="modal-body">
                                Are you sure want to delete this comment?
                            </div>
                            <div class="modal-footer">
                                <button id="btnDelete" class="btn bg-danger">
                                    Delete
                                </button>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            }
        </div>
    </div>
</div>

WebApplication3/Views/Shared/_CommentPartialAdmin.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject UserManager<ApplicationUser> UserManager
@model Comment


<table class="table">
    <tbody>
        <tr>
            <td>
                <div class="row justify-content-center">
                    <div class="col-8">
                        <b>@Model.CommentAuthor</b>
                        <p><textarea class="form-control" readonly style="width: 450px">@Model.CContent</textarea></p>
                        <p>@Model.PostedOn.ConvertTime(Context)</p>
                        <hr />
                    </div>
                </div>
            </td>
            <td>

            </td>
            <td>

            </td>
            <td>
                <div class="col col-1">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <form method="post" asp-action="ApplyComment" asp-controller="PostManager" asp-route-id="@Model.CommentId" asp-route-postId="@Model.PostId"
                                  data-ajax="true" data-ajax-mode="replace" data-ajax-update="#manageComments" enctype="multipart/form-data">
                                <div class="input-group">
                                    <span class="input-group-btn">
                                        <button class="btn btn-success" style="height:40px;width:105px">@Localizer["Apply"]</button>
                                    </span>
                                </div>
                            </form>
                            <form method="post" asp-action="RemoveComment" asp-controller="PostManager" asp-route-id="@Model.CommentId" asp-route-postId="@Model.PostId"
                                  data-ajax="true" data-ajax-mode="replace" data-ajax-update="#manageComments" enctype="multipart/form-data">
                                <div class="input-group">
                                    <span class="input-group-btn">
                                        <button class="btn btn-danger" style="height:40px;width:105px">@Localizer["Decline"]</button>
                                    </span>
                                </div>
                            </form>
                        </span>
                    </div>
                </div>
            </td>
        </tr>
    </tbody>
</table>

WebApplication3/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@using WebApplication3
@addTagHelper *, WebApplication3

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BLOGCreator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/like.css" />
    @*<link rel="stylesheet" href="~/css/notification.css"/>*@
    @*<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-success border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BLOGCreator</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Create">@Localizer["CreatePost"]</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer["Privacy"]</a>
                        </li>*@

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BLOGCreator - <a asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer["Privacy"]</a>
            @await Html.PartialAsync("_SelectLanguagePartial")
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/aspnet-signalr/signalr.min.js"></script>
    <script src="~/ckeditor/ckeditor.js" type="text/javascript"></script>
@*    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.js"></script>*@
    <script src="~/js/time.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript">CKEDITOR.replace('editor1');</script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebApplication3/Views/Shared/_PostLastPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@model WebApplication3.Models.Post
<div class="wrapper">
    <p>
        @if (UserManager.FindByNameAsync(Model.Author).Result.ProfilePicture != null)
        {
            <img style="width:40px; height:40px; object-fit:cover; border-radius:30px" src="data:image/*;base64,@(Convert.ToBase64String(UserManager.FindByNameAsync(Model.Author).Result.ProfilePicture))">
        }
    </p>
    <p>@Model.Author</p>
    <p>@Model.PostedOn.ConvertTime(Context)</p>
    <h4>
        <a asp-controller="Home" asp-action="Details" asp-route-id="@Model.Id">
            @Model.Title
        </a>
    </h4>
    <textarea asp-for="ShortDescription" class="form-control" rows="3" readonly>
        <p>@Model.ShortDescription</p>
    </textarea>
    <hr />
</div>    

WebApplication3/Views/Shared/_PostPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@model WebApplication3.Models.Post

<div class="page-wrapper">
    <div class="left-panel-wrapper">
        <div class="left-panel">
            <p>
                @if (UserManager.FindByNameAsync(Model.Author).Result.ProfilePicture != null)
                {
                    <img style="width:40px; height:40px; object-fit:cover; border-radius:30px" src="data:image/*;base64,@(Convert.ToBase64String(UserManager.FindByNameAsync(Model.Author).Result.ProfilePicture))">
                }
            </p>
            <p>@Model.Author</p>
            <p>@Model.PostedOn.ConvertTime(Context)</p>
        </div>
        <hr />
    </div>
    <div class="content-wrapper">
        <div class="content">                 
                <div class="input-group">
                    <h4>                                            
                        <a asp-controller="Home" asp-action="Details" asp-route-id="@Model.Id">
                            @Model.Title
                        </a>                  
                    </h4>                  
                </div>           
            <textarea asp-for="ShortDescription" class="form-control" rows="3" readonly>
            <p>@Model.ShortDescription</p>
            </textarea>
        </div>
    </div>
</div>

WebApplication3/Views/Shared/_PostPartialAdmin.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@model (WebApplication3.Models.Post, WebApplication3.Models.Comment)

<div class="page-wrapper">
    <div class="left-panel-wrapper">
        <div class="left-panel">
            <p>
                @if (UserManager.FindByNameAsync(Model.Item1.Author).Result.ProfilePicture != null)
                {
                    <img style="width:40px; height:40px; object-fit:cover; border-radius:30px" src="data:image/*;base64,@(Convert.ToBase64String(UserManager.FindByNameAsync(Model.Item1.Author).Result.ProfilePicture))">
                }
            </p>
            <p>@Model.Item1.Author</p>
            <p>@Model.Item1.PostedOn.ConvertTime(Context)</p>
        </div>
        <hr />
    </div>
    <div class="content-wrapper">
        <div class="content">
            <div class="input-group">
                <h4>
                    @if ((User.IsInRole("Admin") || User.IsInRole("Moderator")) && (!Model.Item1.Posted || !Model.Item2.CommentPosted))
                    {
                        <a asp-controller="PostManager" asp-action="Details" asp-route-postId="@Model.Item1.Id" asp-route-id="@Model.Item2.CommentId">
                            @Model.Item1.Title
                        </a>
                    }
                    else
                    {
                        <a asp-controller="Home" asp-action="Details" asp-route-id="@Model.Item1.Id">
                            @Model.Item1.Title
                        </a>
                    }

                </h4>
            </div>
            <textarea asp-for="Item1.ShortDescription" class="form-control" rows="3" readonly>
            <p>@Model.Item1.ShortDescription</p>
            </textarea>
        </div>
    </div>
</div>

WebApplication3/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
}

<form asp-controller="Home" asp-action="SetLanguage" style="display: inline;margin-left: 10px;"
      asp-route-returnUrl="@Context.Request.Path"
      method="post" >
      <select name="culture" onchange="this.form.submit();"
                      asp-for="@requestCulture.RequestCulture.UICulture.Name"
                      asp-items="cultureItems"></select>
</form>