WebApplication3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WebApplication3.Data;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private ApplicationDbContext db;
        UserManager<ApplicationUser> _userManager;
        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            db = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string searchString, string postCategory, int page=1)
        {
            int pageSize = 5;
            var posts = from p in db.Posts select p;
            IQueryable<string> categoryQuery = from p in db.Categories orderby p.Title select p.Title;

            if (!String.IsNullOrEmpty(searchString))
            {
                posts = posts.Where(s => s.Title.Contains(searchString));
            }            
            if (!String.IsNullOrEmpty(postCategory))
            {
                posts = posts.Where(p => p.Category.Title == postCategory);
            }
            var count = await posts.CountAsync();
            var items = await posts.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            var postVm = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Categories = new SelectList(await categoryQuery.Distinct().ToListAsync()),                
                Posts = items
            };
            return View(postVm);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            if (!db.Posts.Contains(db.Posts.Find(id)))
            {
                return RedirectToAction("DeletedPost");
            }
            var postCommentVm = new CommentViewModel
            {
                Post = db.Posts.Find(id),
                //PostComment = new Comment {PostId = id}
                Comments = db.Comments.ToList()
            };
            
            return View(postCommentVm);
        }

        public IActionResult DeletedPost()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Details(Comment comment, int id)
        {
            if (ModelState.IsValid)
            {
                comment.PostedOn = DateTime.Now;                
                comment.CommentAuthor = _userManager.GetUserName(this.User);                
                db.Add(comment);
                
                db.SaveChanges();
                
                var postCommentVm = new CommentViewModel
                {
                    Post = db.Posts.Find(id),
                    Comments = db.Comments.ToList()
                };
                return View("Details", postCommentVm);
            }
            return View("Details");
        }

        [HttpPost]
        public IActionResult Delete(int id, string author)
        {           
            if (ModelState.IsValid)
            {                              
                db.Posts.Remove(db.Posts.Find(id));                
                db.SaveChanges();
            }
            return RedirectToAction("Index");            
        }

        [HttpPost]
        public IActionResult DeleteCommentUser(int id, int postId)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Remove(db.Comments.Find(id));
                db.SaveChanges();
            }
            return RedirectPermanent($"~/Home/Details/{postId}");
        }

        [HttpPost]
        public IActionResult DeleteComment(int id, int postId)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Remove(db.Comments.Find(id));
                db.SaveChanges();
            }
            return RedirectToAction("CommentList", new { id = postId });
        }

        public PartialViewResult CommentList(int id)
        {
            var postCommentVm = new CommentViewModel
            {
                Post = db.Posts.Find(id),
                Comments = db.Comments.ToList()
            };
            return PartialView(postCommentVm);
        }

        [Authorize]
        public IActionResult Like(int commentId, int postId)
        {
            if (ModelState.IsValid)
            {
                var comment = db.Comments.Find(commentId);
                var like = new Like
                {
                    Username = _userManager.GetUserName(this.User),
                    CommentId = commentId
                };
                if (db.Likes
                    .Where(l => l.CommentId == commentId)
                    .Where(l => l.Username == _userManager.GetUserName(this.User))
                    .Any())
                {
                    var likes = db.Likes
                    .Where(l => l.CommentId == commentId)
                    .Where(l => l.Username == _userManager.GetUserName(this.User))
                    .ToList();
                    _logger.LogInformation("tuta");
                    db.Likes.Remove(likes[0]);
                    comment.LikesCount--;
                }
                else
                {
                    db.Likes.Add(like);                    
                    comment.LikesCount++;                              
                }
                db.SaveChanges();
            }
            //return RedirectToAction("_CommentPartial", new { id = CommentId});
            return RedirectToAction("CommentList", new { id = postId });
        }

        public PartialViewResult _CommentPartial(int id)
        {
            return PartialView(db.Comments.Find(id));
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1)}
            );
            return LocalRedirect(returnUrl);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

WebApplication3/ViewComponents/LastPostsViewComponent.cs
//using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Data;
using WebApplication3.Models;

namespace WebApplication3.ViewComponents
{
    public class LastPostsViewComponent : ViewComponent
    {
        private ApplicationDbContext db;

        public LastPostsViewComponent(ApplicationDbContext context)
        {
            db = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int howMany = 3)
        {
            var posts = await db.Posts
                .OrderByDescending(a => a.PostedOn)
                .Where(p => p.Posted != false)
                .Take(howMany)
                .ToListAsync();
            return View(posts);
        }
    }
}

WebApplication3/Views/Home/CommentList.cshtml
@model WebApplication3.Models.CommentViewModel


<div class="listing" id="commentList">
    @foreach (var comment in Model.Comments)
    {
        @if (comment.CommentPosted == true && comment.PostId == Model.Post.Id)
        {
            <lu>
                @await Html.PartialAsync("_CommentPartial", comment)
            </lu>
        }
    }
</div>

WebApplication3/Views/Home/DeletedPost.cshtml
@{
    ViewData["Title"] = "DeletedPost";
}

<h2>Sorry, but that article has been already deleted.</h2>

WebApplication3/Views/Home/Details.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject UserManager<ApplicationUser> UserManager
@model WebApplication3.Models.CommentViewModel
@{
    var midDel = "myModalDel" + Model.Post.Id;
    var tmDel = "#myModalDel" + Model.Post.Id;
    var mid = "myModal" + Model.Post.Id;
    var tm = "#myModal" + Model.Post.Id;
}

<div class="page-wrapper">
    <ul class="col-md-8">
        @await Html.PartialAsync("_PostPartial", Model.Post)
        @if (UserManager.GetUserAsync(User).Result != null && UserManager.GetUserAsync(User).Result.UserName == Model.Post.Author && !User.IsInRole("Admin") && !User.IsInRole("Moderator"))
        {
            <span class="input-group-btn">
                <button class="btn btn-danger" data-toggle="modal" data-target="@tmDel">@Localizer["Delete"]</button>
            </span>

        }
        @if ((User.IsInRole("Admin") || User.IsInRole("Moderator")) && Model.Post.Posted == true)
        {
            <span class="input-group-btn">
                <button class="btn btn-danger" data-toggle="modal" data-target="@tmDel">@Localizer["Delete"]</button>
            </span>
        }
        <form method="post" asp-action="Delete" asp-controller="Home" asp-route-id="@Model.Post.Id" asp-route-author="@Model.Post.Author">
            <div class="modal fade" id="@midDel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myModalLabel">@Localizer["DeleteConf"]</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        </div>
                        <div class="modal-body">
                            @Localizer["Question"]
                        </div>
                        <div class="modal-footer">
                            <button class="btn bg-danger">@Localizer["Delete"]</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">@Localizer["Close"]</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <hr />
        <p>@Html.Raw(Model.Post.Description)</p>
    </ul>
    <div class="right-panel-wrapper">
        <div class="right-panel">
            @await Component.InvokeAsync("LastPosts", new { howMany = 2 })
        </div>
    </div>
</div>

<h2>@Localizer["Comments"]</h2>
<div class="row justify-content-center">
    <div class="col-8">
        <form asp-action="Details" asp-controller="Home" method="post">
            <div class="form-group">
                @*<input type="text" name="CContent">*@
                <input type="hidden" name="PostId" value="@Model.Post.Id">
                <textarea name="CContent" class="form-control"></textarea>
                <span name="CContent" class="text-danger"></span>
            </div>
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="@tm">
                @Localizer["Submit"]
            </button>
            <div class="modal fade" id="@mid" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myModalLabel">@Localizer["SubmitConf"]</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        </div>
                        <div class="modal-body">
                            @Localizer["Question2"]
                        </div>
                        <div class="modal-footer">
                            <input type="submit" class="btn btn-success" value="@Localizer["Submit"]">
                            <button type="button" class="btn btn-default" data-dismiss="modal">@Localizer["Close"]</button>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>
    <div class="row justify-content-center" id="comments">
        @await Html.PartialAsync("~/Views/Home/CommentList.cshtml", Model)
    </div>
</div>

WebApplication3/Views/Home/Index.cshtml
@*@model IEnumerable<WebApplication3.Models.Post>*@
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model WebApplication3.Models.IndexViewModel
@addTagHelper *, WebApplication3
@{
    ViewData["Title"] = @Localizer["HomePage"];

}

<div class="page-wrapper">
    <ul class="col-md-8" id="posts">
        @await Html.PartialAsync("~/Views/Home/PostList.cshtml", Model.Posts)
    </ul>
    <div class="right-panel-wrapper">
        <div class="right-panel">
            <form method="get" asp-controller="Home" asp-action="Index">
                <p>
                    <select asp-for="PostCategory" asp-items="Model.Categories">
                        <option value="">@Localizer["All"]</option>
                    </select>
                    <input type="text" name="SearchString">
                    <input type="submit" value=@Localizer["Search"]>
                </p>
            </form>
            @await Component.InvokeAsync("LastPosts", new { howMany = 2 })
        </div>
    </div>
</div>
<page-link page-view-model="Model.PageViewModel" page-action="Index"></page-link>
@*<script src="~/js/notification.js"></script>
<script src="~/js/signalr/jquery.signalR.min.js"></script>
<script src="~/lib/signalr.js/jquery.signalR.js"></script>
<script src="~/lib/aspnet-signalr/signalr.js"></script>*@

WebApplication3/Views/Home/PostList.cshtml
@*@model WebApplication3.Models.CategoryViewModel*@
@model IEnumerable<WebApplication3.Models.Post>

<div class="listing" id="postList">
    @foreach (var post in Model)
    {
        @if (post.Posted != false)
        {
            <li>
                @await Html.PartialAsync("_PostPartial", post)
            </li>
        }

    }
</div>